part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const LOGIN = _Paths.LOGIN;
  static const DEPTMANAGEMENT = _Paths.DEPTMANAGEMENT;
  static const DEPTMANAG = _Paths.DEPTMANAG;
  static const STORESLIST = _Paths.STORESLIST;
  static const STOREDETAILS = _Paths.STOREDETAILS;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const CHOOSEACCOUNT = _Paths.CHOOSEACCOUNT;
  static const AUTHSCREEN = _Paths.AUTHSCREEN;
  static const MANAGECREDITORS = _Paths.MANAGECREDITORS;
  static const EPAYMENT = _Paths.EPAYMENT;
  static const MERCHANTHOME = _Paths.MERCHANTHOME;
  static const CUSTOMERSMANAGEMENT = _Paths.CUSTOMERSMANAGEMENT;
  static const ADDCUSTOMERSCREEN = _Paths.ADDCUSTOMERSCREEN;
  static const ADDDEPTSCREEN = _Paths.ADDDEPTSCREEN;
  static const EDITCUSTOMERSCREEN = _Paths.EDITCUSTOMERSCREEN;

  static const FRONTPAGE = _Paths.FRONTPAGE;
  static const CREATEACCOUNT = _Paths.CREATEACCOUNT;
  static const MAINPAGE = _Paths.MAINPAGE;
  static const SETTINGS = _Paths.SETTINGS;

  static const USERINFO = _Paths.USERINFO;
  static const CHILDRENLIST = _Paths.CHILDRENLIST;
  static const ADDCHILD = _Paths.ADDCHILD;
  static const CHILDINFO = _Paths.CHILDINFO;
  static const TEMPPAGE = _Paths.TEMPPAGE;
  static const CHILDTEMPLIST = _Paths.CHILDTEMPLIST;
  static const FORGETPASSWORD = _Paths.FORGETPASSWORD;

  static const SPLASHSCREEN = _Paths.SPLASHSCREEN;
  static const SIGNUPSCREEN = _Paths.SIGNUPSCREEN;

  static const HOMESCREEN = _Paths.HOMESCREEN;
  static const PATIENTINFOSCREEN = _Paths.PATIENTINFOSCREEN;
  static const CHOOSESTATUS = _Paths.CHOOSESTATUS;
  static const CHATSCREEN = _Paths.CHATSCREEN;
  static const NEARESTHOSPITALSCREEN = _Paths.NEARESTHOSPITALSCREEN;
  static const EDITPROFILESCREEN = _Paths.EDITPROFILESCREEN;
  static const ANOTHERPATIENTINFOSCREEN = _Paths.ANOTHERPATIENTINFOSCREEN;
  static const CHOOSEACCOUNTSCREEN = _Paths.CHOOSEACCOUNTSCREEN;
  static const LOGINADMINSCREEN = _Paths.LOGINADMINSCREEN;
  static const LOGINHOSPITALSCREEN = _Paths.LOGINHOSPITALSCREEN;
  static const ADMINHOMESCREEN = _Paths.ADMINHOMESCREEN;
  static const ADDADMINSCREEN = _Paths.ADDADMINSCREEN;
  static const LISTADMINSSCREEN = _Paths.LISTADMINSSCREEN;
  static const ADDHOSPITALSCREEN = _Paths.ADDHOSPITALSCREEN;
  static const LISTHOSPITALSSCREEN = _Paths.LISTHOSPITALSSCREEN;
  static const HOSPITALHOMESCREEN = _Paths.HOSPITALHOMESCREEN;
  static const EDITADMINPROFILESCREEN = _Paths.EDITADMINPROFILESCREEN;
  static const STARTEMERGENCYSCREEN = _Paths.STARTEMERGENCYSCREEN;
  static const CHOOSESTATUSFORPATIENT = _Paths.CHOOSESTATUSFORPATIENT;
  static const MAPPAGESCREEN = _Paths.MAPPAGESCREEN;
    static const REQUESTSSCREEN = _Paths.REQUESTSSCREEN;
        static const CHATLISTSCREEN = _Paths.CHATLISTSCREEN;

        static const LISTCLINCSSCREEN = _Paths.LISTCLINCSSCREEN;
        static const ADDCLINICSCREEN = _Paths.ADDCLINICSCREEN;

}

abstract class _Paths {
  static const LOGIN = '/LOGIN';
  static const DEPTMANAGEMENT = '/DEPTMANAGEMENT';
  static const DEPTMANAG = '/DEPTMANAG';
  static const STORESLIST = '/STORESLIST';
  static const STOREDETAILS = '/STOREDETAILS';
  static const ONBOARDING = '/ONBOARDING';
  static const CHOOSEACCOUNT = '/CHOOSEACCOUNT';
  static const AUTHSCREEN = '/AUTHSCREEN';
  static const MANAGECREDITORS = '/MANAGECREDITORS';
  static const EPAYMENT = '/EPAYMENT';
  static const MERCHANTHOME = '/MERCHANTHOME';
  static const CUSTOMERSMANAGEMENT = '/CUSTOMERSMANAGEMENT';
  static const ADDCUSTOMERSCREEN = '/ADDCUSTOMERSCREEN';
  static const ADDDEPTSCREEN = '/ADDDEPTSCREEN';
  static const EDITCUSTOMERSCREEN = '/EDITCUSTOMERSCREEN';

  static const FRONTPAGE = '/FRONTPAGE';
  static const CREATEACCOUNT = '/CREATEACCOUNT';
  static const MAINPAGE = '/MAINPAGE';
  static const SETTINGS = '/SETTINGS';
  static const USERINFO = '/USERINFO';
  static const CHILDRENLIST = '/CHILDRENLIST';
  static const ADDCHILD = '/ADDCHILD';
  static const CHILDINFO = '/CHILDINFO';
  static const TEMPPAGE = '/TEMPPAGE';

  static const CHILDTEMPLIST = '/CHILDTEMPLIST';
  static const FORGETPASSWORD = '/FORGETPASSWORD';
  static const SPLASHSCREEN = '/SPLASHSCREEN';
  static const SIGNUPSCREEN = '/SIGNUPSCREEN';
  static const HOMESCREEN = '/HOMESCREEN';
  static const PATIENTINFOSCREEN = '/PATIENTINFOSCREEN';
  static const CHOOSESTATUS = '/CHOOSESTATUS';
  static const CHATSCREEN = '/CHATSCREEN';
  static const NEARESTHOSPITALSCREEN = '/NEARESTHOSPITALSCREEN';
  static const EDITPROFILESCREEN = '/EDITPROFILESCREEN';
  static const ANOTHERPATIENTINFOSCREEN = '/ANOTHERPATIENTINFOSCREEN';
  static const CHOOSEACCOUNTSCREEN = '/CHOOSEACCOUNTSCREEN';
  static const LOGINADMINSCREEN = '/LOGINADMINSCREEN';
  static const LOGINHOSPITALSCREEN = '/LOGINHOSPITALSCREEN';
  static const ADMINHOMESCREEN = '/ADMINHOMESCREEN';
  static const ADDADMINSCREEN = '/ADDADMINSCREEN';
  static const LISTADMINSSCREEN = '/LISTADMINSSCREEN';
  static const ADDHOSPITALSCREEN = '/ADDHOSPITALSCREEN';
  static const LISTHOSPITALSSCREEN = '/LISTHOSPITALSSCREEN';
  static const HOSPITALHOMESCREEN = '/HOSPITALHOMESCREEN';
  static const EDITADMINPROFILESCREEN = '/EDITADMINPROFILESCREEN';
  static const STARTEMERGENCYSCREEN = '/STARTEMERGENCYSCREEN';
  static const CHOOSESTATUSFORPATIENT = '/CHOOSESTATUSFORPATIENT';
  static const MAPPAGESCREEN = '/MAPPAGESCREEN';
    static const REQUESTSSCREEN = '/REQUESTSSCREEN';
        static const CHATLISTSCREEN = '/CHATLISTSCREEN';
           static const LISTCLINCSSCREEN ='/LISTCLINCSSCREEN';
        static const ADDCLINICSCREEN = '/ADDCLINICSCREEN';


}
